import { z } from "zod";
import { jobDrivers, storageDrivers } from "@/config/video";

const envSchema = z.object({
  NEXT_PUBLIC_APP_NAME: z.string().min(1).default("VideoForge AI"),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_FIREBASE_API_KEY: z.string().optional(),
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string().optional(),
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string().optional(),
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string().optional(),
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string().optional(),
  NEXT_PUBLIC_FIREBASE_APP_ID: z.string().optional(),
  NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST: z.string().optional(),
  FIREBASE_PROJECT_ID: z.string().optional(),
  FIREBASE_CLIENT_EMAIL: z.string().optional(),
  FIREBASE_PRIVATE_KEY: z.string().optional(),
  FIREBASE_AUTH_EMULATOR_HOST: z.string().optional(),
  NEXT_PUBLIC_SUPABASE_URL: z.string().url().optional(),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  SUPABASE_JWT_SECRET: z.string().optional(),
  DATABASE_URL: z.string().optional(),
  VIDEO_PROVIDER: z.string().default("fal"),
  VIDEO_PROVIDER_API_KEY: z.string().optional(),
  VIDEO_PROVIDER_WEBHOOK_SECRET: z.string().optional(),
  FAL_API_KEY: z.string().optional(),
  FAL_QUEUE_BASE_URL: z.string().url().default("https://queue.fal.run"),
  FAL_KLING_TEXT_MODEL: z.string().default("fal-ai/kling-video/v2.5-turbo/pro/text-to-video"),
  FAL_KLING_IMAGE_MODEL: z.string().default("fal-ai/kling-video/v2.5-turbo/pro/image-to-video"),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL: z.string().default("gpt-5-mini"),
  DEMO_USER_EMAIL: z.string().email().default("alex@northstarhq.com"),
  DEMO_USER_NAME: z.string().min(1).default("Alex Morgan"),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  STRIPE_PRICE_DEMO: z.string().optional(),
  STRIPE_PRICE_LITE: z.string().optional(),
  STRIPE_PRICE_PRO: z.string().optional(),
  STRIPE_PRICE_BUSINESS: z.string().optional(),
  STORAGE_DRIVER: z.enum(storageDrivers).default("mock"),
  SUPABASE_STORAGE_BUCKET: z.string().default("videoforge-assets"),
  R2_ACCOUNT_ID: z.string().optional(),
  R2_ACCESS_KEY_ID: z.string().optional(),
  R2_SECRET_ACCESS_KEY: z.string().optional(),
  R2_BUCKET: z.string().optional(),
  R2_PUBLIC_URL: z.string().optional(),
  JOB_DRIVER: z.enum(jobDrivers).default("mock"),
  UPSTASH_REDIS_REST_URL: z.string().optional(),
  UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
  APP_LOG_LEVEL: z.enum(["debug", "info", "warn", "error"]).default("info"),
});

export const env = envSchema.parse(process.env);
