import { videoGenerationSchema, type VideoGeneration } from "@/lib/schemas/video";

export const seededVideoGenerations: VideoGeneration[] = [
  {
    id: "b7f0f707-d3ff-448b-b3e2-e43011d1fb95",
    userId: "0ed7596f-f5e7-470e-9d3a-d9e1085ed267",
    projectName: "Q2 Skincare Launch Reel",
    prompt:
      "Create a crisp vertical ecommerce ad for a new skincare launch with premium product close-ups, founder quote, social proof and a high-converting CTA.",
    negativePrompt: "Avoid childish colors, shaky camera and low-contrast scenes.",
    generationType: "text-to-video",
    status: "completed",
    aspectRatio: "9:16",
    resolution: "720p",
    durationSeconds: 10,
    style: "performance-ads",
    templateSlug: "ecommerce-flash-sale",
    sourceImageUrl: null,
    providerKey: "mock",
    providerJobId: "mock-job-001",
    progress: 100,
    estimatedCredits: 11,
    consumedCredits: 11,
    errorCode: null,
    errorMessage: null,
    createdAt: "2026-03-11T05:00:00.000Z",
    updatedAt: "2026-03-11T05:00:42.000Z",
    completedAt: "2026-03-11T05:00:42.000Z",
  },
  {
    id: "7dde72a3-cacc-4a5d-b1fd-f55707d40c08",
    userId: "0ed7596f-f5e7-470e-9d3a-d9e1085ed267",
    projectName: "Agency Results Recap",
    prompt:
      "Create a widescreen agency proof video showing campaign metrics, client logos, service highlights and a CTA for a strategy call.",
    negativePrompt: null,
    generationType: "text-to-video",
    status: "processing",
    aspectRatio: "16:9",
    resolution: "720p",
    durationSeconds: 10,
    style: "sleek-corporate",
    templateSlug: "agency-results-recap",
    sourceImageUrl: null,
    providerKey: "mock",
    providerJobId: "mock-job-002",
    progress: 61,
    estimatedCredits: 11,
    consumedCredits: null,
    errorCode: null,
    errorMessage: null,
    createdAt: "2026-03-11T06:00:00.000Z",
    updatedAt: "2026-03-11T06:00:25.000Z",
    completedAt: null,
  },
].map((generation) => videoGenerationSchema.parse(generation));
