export const planCatalog = [
  {
    id: "demo",
    name: "Demo",
    description: "Perfect for testing one polished 10-second AI video before upgrading.",
    monthlyPrice: 4.99,
    monthlyCredits: 11,
    includedVideos: 1,
    standardDurationSeconds: 10,
    maxDurationSeconds: 10,
    historyLimitDays: 7,
    concurrencyLimit: 1,
    priority: "standard",
    features: [
      "1 AI video / month",
      "10-second commercial format",
      "AI idea-to-brief assistant",
      "Editable prompt before render",
    ],
  },
  {
    id: "lite",
    name: "Lite",
    description: "For solo creators who need a handful of short conversion-focused videos each month.",
    monthlyPrice: 19.99,
    monthlyCredits: 55,
    includedVideos: 5,
    standardDurationSeconds: 10,
    maxDurationSeconds: 10,
    historyLimitDays: 30,
    concurrencyLimit: 1,
    priority: "standard",
    features: [
      "5 AI videos / month",
      "10-second vertical or square videos",
      "AI hook, CTA and copy enhancement",
      "Prompt templates and history",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    description: "For marketers and ecommerce teams shipping short-form video every week.",
    monthlyPrice: 34.99,
    monthlyCredits: 110,
    includedVideos: 10,
    standardDurationSeconds: 10,
    maxDurationSeconds: 10,
    historyLimitDays: 90,
    concurrencyLimit: 2,
    priority: "priority",
    features: [
      "10 AI videos / month",
      "Up to 10-second renders",
      "Text-to-video and image-to-video",
      "Priority generation queue",
    ],
  },
  {
    id: "business",
    name: "Business",
    description: "For agencies and brands that need steady short-form video output with more room to iterate.",
    monthlyPrice: 64.99,
    monthlyCredits: 220,
    includedVideos: 20,
    standardDurationSeconds: 10,
    maxDurationSeconds: 10,
    historyLimitDays: 180,
    concurrencyLimit: 4,
    priority: "highest",
    features: [
      "20 AI videos / month",
      "10-second premium renders",
      "Text-to-video and image-to-video",
      "Highest priority queue",
      "Longer history and admin controls",
    ],
  },
] as const;

export type PlanId = (typeof planCatalog)[number]["id"];
